#!/bin/bash
# FILE: ssh-local.sh

#----------------------------------#
#      Local SSH Login Agent       #
#                                  #
# Author: codejedi365              #
# Date:   14 Oct 2020              #
#----------------------------------#

# Interactive prompt
# shows available usernames, asks for remote ip address, tells you the port
# interactive prompt by default
# additionally any other parameters will modify individual parameters
# could be included as Environment variables specified as
#

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )";   # source code location
WRK_DIR="$PWD";                                             # current location user is
[ -f "$WRK_DIR/users" ] && . "$WRK_DIR"/users || USERS=()              #include users list

# Default Vars
[ -z "$DEFAULT_SSH_PORT" ] && DEFAULT_SSH_PORT=22;
[ -n "$DEFAULT_rHOSTNAME" ] && [ -z "$(grep -E '(\.local)$' <(echo "$DEFAULT_rHOSTNAME"))" ] && DEFAULT_rHOSTNAME="${DEFAULT_rHOSTNAME}.local";
MODE_LAZY=false
MODE_PORTFWD=false
MODE_QUIET=false

usage() {
    echo "Usage: $0 [-hlfqT] [-a <address>] [-p <port>] [-u <user>]" 1>&2; exit 1;
}
help() {
    echo ""
    echo "SSH Local Login Agent"
    echo "---------------------"
    echo "Interactive SSH connection initializer to local device"
    echo ""
    usage | echo;
    echo "Available Options: "
    echo "  -h  Help"
    echo "  -a  Hostname or IPv4 address"
    echo "  -p  Remote port to connect to"
	echo "         default: $DEFAULT_SSH_PORT"
    echo "  -l  Lazy mode or non-interactive mode and if variable is missing it fails or uses default"
    echo "  -u  username"
    echo "  -f  Activate Port Forwarding mode"
    echo "         default: OFF"
	echo "  -q  Execute quietly"
	echo "  -T  Activate Test Mode. Builds command but does not execute connection"
    echo ""
    exit 0;
}
print_banner() {
	echo "";
    echo "===================";
    echo "| SSH Local Login |";
    echo "===================";
	echo "";
}

interact() {

    if [ -z "$REMOTE_ADDRESS" ] && [ "$MODE_LAZY" = false ]; then
        local valid=false
        local dest=""
        DEFAULT_PROMPT=`[ -n "$DEFAULT_rHOSTNAME" ] && echo " [$DEFAULT_rHOSTNAME]" || echo ""`
        while [ "$valid" = false ]; do
            read -e -p "Hostname/IPv4 Address${DEFAULT_PROMPT}: " dest;
            
            if [ -n "$(grep -E '^([A-Za-z0-9_-]+[A-Za-z0-9])(\.local)?$' <(echo "$dest"))" ]; then			# Check if address matches a HOSTNAME
                [ -z "$(grep -E '(\.local)$' <(echo "$dest"))" ] && dest="$dest.local";
                valid=true

            elif [ -n "$(grep -E '^(([0-9]{1,3}\.){3}[0-9]{1,3})$' <(echo "$dest"))" ]; then		# Check if address matches an IPv4 address
                valid=true

            elif [ -z "$dest" ] && [ -n "$DEFAULT_rHOSTNAME" ]; then # empty input when there is a default
                dest=$DEFAULT_rHOSTNAME
                valid=true
            
            elif [ -z "$dest" ]; then       # empty input when there is NOT a default
                continue

            else
                echo 1>&2 "Invalid Input received. Please enter either a hostname or an IPv4 address.";
            fi
        done
        REMOTE_ADDRESS="$dest"
        echo "ADDRESS=$REMOTE_ADDRESS"
    fi
	
}

# Required env vars
#  REMOTE_ADDRESS
main() {
	if [ "$MODE_QUIET" = false ]; then
		print_banner
	fi
	interact
	if [ -f "$SRC_DIR/.ssh-connect" ]; then
		. "$SRC_DIR/.ssh-connect" -q "${args2pass# }"
		if [ "$?" == 1 ]; then
			echo "Connection Failed. Exiting...";
			exit 1
		fi
	else 
		echo "FILE ./.ssh-connect NOT FOUND. Exiting...";
		exit 1
	fi
}

# Process line args
processArgs() {
	local OPTIND;
	while getopts ":a:u:p:hlfqT" o; do               # process & check command line options
		case "${o}" in
			a)
				local address=${OPTARG}
				if [ -n "$(grep -E '^([A-Za-z0-9_-]+[A-Za-z0-9])(\.local)?$' <(echo "$address"))" ]; then			# Check if address matches a HOSTNAME
					[ -z "$(grep -E '(\.local)$' <(echo "$address"))" ] && address="$address.local";

				elif [ -z "$(grep -E '^(([0-9]{1,3}\.){3}[0-9]{1,3})$' <(echo "$address"))" ]; then		# Check if address matches an IPv4 address
					usage
				fi
				REMOTE_ADDRESS="$address"
				;;
			u)
				[ -z "${OPTARG}" ] && usage;
				args2pass="$args2pass -${o} ${OPTARG}"
				;;
			p)
				[[ "${OPTARG}" < 1 ]] && usage;
				args2pass="$args2pass -${o} ${OPTARG}"
				;;
			h)
				help
				;;
			l)
				[ -n "${OPTARG}" ] && usage; 
				args2pass="$args2pass -${o}"
				MODE_LAZY=true
				;;
			f)
				[ -n "${OPTARG}" ] && usage; 
				args2pass="$args2pass -${o}"
				;;
			T)
				[ -n "${OPTARG}" ] && usage; 
				args2pass="$args2pass -${o}"
				;;
			q)
				MODE_QUIET=true
				;;
			*)
				usage
				;;
		esac
	done
	shift $((OPTIND-1))
}

# ---------------------------
# Autorun - Ingest line args
# ---------------------------
processArgs "$@";

main                    # Run Main Loop
